package com.payment.queries;



public class QueryConstant {
	
	
	public static StringBuffer createTables = new StringBuffer(
	    " create table GATEWAY"+
        " (GATEWAY_ID   int    GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY ,"+
        " GATEWAY_NAME  varchar(100) not null ); "+
   
       " create table USER "+
       " (USER_ID                        int             GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,"+
       " MAIL_ID                       varchar(50)    not null ,"+
       " PASSWORD                       varchar(50)   not null );"+
       
       
      " create table ACCEPTED_PAYMENT_GATEWAYS "+
      " (USER_ID                        int  ,"+
      " GATEWAY_ID                      int  ,"+
      " FOREIGN KEY(USER_ID) REFERENCES USER (USER_ID) ,"+
      " FOREIGN KEY(GATEWAY_ID) REFERENCES GATEWAY (GATEWAY_ID) ,"+
      " CONSTRAINT PK_KEY PRIMARY KEY(USER_ID, GATEWAY_ID)); "+
       
       
       " create table INVOICE "+
       " ( INVOICE_ID int   GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,"+
       " USER_ID     int not null ,"+
       " TO_MAIL_ID                     varchar(50) not null,"+
       " VALUE                          int         not null,"+
       " STATE                          varchar(50) not null,"+
       " FOREIGN KEY(USER_ID) REFERENCES USER (USER_ID)); commit;"
     
   );
	
    /*INVOICE QUERIES*/
	public static StringBuffer getAllInvoices = new StringBuffer("select * from invoice");
	public static StringBuffer getInvoicesByUser = new StringBuffer("select * from invoice where user_id=?");
	
	public static StringBuffer insertInvoice = new StringBuffer("INSERT INTO invoice (user_id,to_mail_id,value,state) VALUES (?,?,?,?)");
	public static StringBuffer updateInvoice = new StringBuffer("update invoice set to=? , value=? , state=? where invoice_id=?");
	public static StringBuffer deleteInvoice = new StringBuffer("delete invoice  where invoice_id=?");
	
	
	/*USER QUERIES*/
	
	public static StringBuffer getUserById = new StringBuffer("select * from invoice where user_id=?");
	public static StringBuffer getUserByMailId = new StringBuffer("select * from invoice where mail_id=?");
	public static StringBuffer insertUser = new StringBuffer("INSERT INTO user (mail_id,password) VALUES (?,?)");
	
	
	
	
	/*GATEWAY QUERIES*/
	public static StringBuffer getGateways = new StringBuffer("select * from gateway");
	
}
